ALTER TABLE SERVICIO
	ADD CONSTRAINT FK_SERVICIO
		FOREIGN KEY (CLIENTE)
		REFERENCES CLIENTE (ID);

ALTER TABLE EJERCICIO
    ADD CONSTRAINT FK_EJERCICIO
        FOREIGN KEY (CLIENTE)
        REFERENCES CLIENTE (ID);


ALTER TABLE CLIENTE
    ADD CONSTRAINT FK_CLIENTE
        FOREIGN KEY (EPS)
        REFERENCES EPS(ID);