CREATE TABLE CLIENTE (
	ID CHAR(15) NOT NULL,
	NOMBRE CHAR(20) NOT NULL,
	APELLIDO CHAR(20) NOT NULL,
	DIRECCION VARCHAR(60),
	GENERO BOOLEAN NOT NULL,
	FECHA_NACIMIENTO DATE NOT NULL,
	TIPO_SANGRE SMALLINT NOT NULL,
	RH BOOLEAN NOT NULL,
	EPS CHAR(5) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE SERVICIO (
	CLIENTE CHAR(15) NOT NULL,
	ID CHAR(5) NOT NULL,
	DESCRIPCION VARCHAR(100) NOT NULL,
	PRIMARY KEY (CLIENTE, ID)
);

CREATE TABLE EPS (
	ID CHAR(5) NOT NULL,
	NOMBRE CHAR(20) NOT NULL,
	PRIMARY KEY (ID)
);

