CREATE TABLE CLIENTE (
	ID CHAR(15) NOT NULL,
	NOMBRE CHAR(20) NOT NULL,
	APELLIDO CHAR(20) NOT NULL,
	DIRECCION VARCHAR(60),
	GENERO BOOLEAN NOT NULL,
	FECHA_NACIMIENTO DATE NOT NULL,
	TIPO_SANGRE SMALLINT NOT NULL,
	RH BOOLEAN NOT NULL,
	EPS INT NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE TELEFONO (
    CLIENTE CHAR(15) NOT NULL,
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    TELEFONO CHAR(15) NOT NULL
);

CREATE TABLE SERVICIO (
	CLIENTE CHAR(15) NOT NULL,
	ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	DESCRIPCION VARCHAR(100) NOT NULL,
	PRIMARY KEY (CLIENTE, ID)
);

CREATE TABLE EPS (
	ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NOMBRE CHAR(20) NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE EJERCICIO (
    CLIENTE CHAR(15) NOT NULL,
    DIA INT NOT NULL,
    ORDEN_SECUENCIAL INT NOT NULL,
    DESCRIPCION CHAR(15) NOT NULL,
    SERIES INT NOT NULL,
    REPETICIONES INT NOT NULL,
    PESO    INT,
    PRIMARY KEY (CLIENTE, DIA, ORDEN_SECUENCIAL)
);


CREATE TABLE MEDIDAS_CORPORALES(
    CLIENTE CHAR(15) NOT NULL,
    FECHA_REGISTRO DATE NOT NULL,
    PESO DECIMAL NOT NULL,
    ESTATURA DECIMAL NOT NULL,
    CINTURA DECIMAL NOT NULL,
    CADERA DECIMAL NOT NULL,
    PIERNA_I DECIMAL NOT NULL,
    PIERNA_D DECIMAL NOT NULL,
    BRAZO_I DECIMAL NOT NULL,
    BRAZO_D DECIMAL NOT NULL,
    GLUTEO_I DECIMAL NOT NULL,
    GLUTEO_D DECIMAL NOT NULL,
    CUELLO DECIMAL NOT NULL,
    HOMBRO_I DECIMAL NOT NULL,
    HOMBRO_D DECIMAL NOT NULL,
    ESPALDA DECIMAL NOT NULL,
    PRIMARY KEY (CLIENTE, FECHA_REGISTRO)
);